[package]
name = "rust-polska"
version = "0.1.0"
authors = ["Michał Papierski <michal@papierski.net>"]
edition = "2018"

[dependencies]
hyper = "0.12.23"
log = "0.4"
pretty_env_logger = "0.3.0"

[target.heroku]
version = "stable"
